# Generated by Django 4.0.6 on 2022-09-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_studreg',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('p_name', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=15)),
                ('sl_course', models.CharField(max_length=15)),
                ('phone', models.IntegerField()),
                ('mark', models.IntegerField()),
                ('place', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
